
DROP TABLE Version;
DROP TABLE IF EXISTS Temperature;

DROP TABLE IF EXISTS Log;
DROP TABLE IF EXISTS LogType;
DROP TABLE IF EXISTS WebSession;
DROP TABLE IF EXISTS UserAgent;

DROP TABLE IF EXISTS UserRole;
DROP TABLE IF EXISTS Role;
DROP TABLE IF EXISTS User;
